import { createGovernanceControlMap } from "../control-map.mjs";
import { PLATFORM_SELF_GOVERNANCE_ADMISSION_IDENTITY_TRUST_CONTROLS } from "./admission-identity-trust.mjs";
import { PLATFORM_SELF_GOVERNANCE_AUDIT_EVIDENCE_LIFECYCLE_CONTROLS } from "./audit-evidence-lifecycle.mjs";
import { PLATFORM_SELF_GOVERNANCE_DATA_STATE_SEMANTICS_CONTROLS } from "./data-state-semantics.mjs";
import { PLATFORM_SELF_GOVERNANCE_PERMISSION_BEHAVIOR_POLICY_CONTROLS } from "./permission-behavior-policy.mjs";
import { PLATFORM_SELF_GOVERNANCE_TRAFFIC_RESOURCE_COST_CONTROLS } from "./traffic-resource-cost.mjs";

export const PLATFORM_SELF_GOVERNANCE_CONTROLS = createGovernanceControlMap(
  PLATFORM_SELF_GOVERNANCE_ADMISSION_IDENTITY_TRUST_CONTROLS,
  PLATFORM_SELF_GOVERNANCE_PERMISSION_BEHAVIOR_POLICY_CONTROLS,
  PLATFORM_SELF_GOVERNANCE_DATA_STATE_SEMANTICS_CONTROLS,
  PLATFORM_SELF_GOVERNANCE_TRAFFIC_RESOURCE_COST_CONTROLS,
  PLATFORM_SELF_GOVERNANCE_AUDIT_EVIDENCE_LIFECYCLE_CONTROLS
);
