import { createGovernanceControlMap } from "../control-map.mjs";
import { PLATFORM_SELF_GOVERNANCE_AUDIT_FACT_VERIFICATION_CONTROLS } from "./audit-fact-verification.mjs";
import { PLATFORM_SELF_GOVERNANCE_DATA_STATE_SEMANTICS_CONTROLS } from "./data-state-semantics.mjs";
import { PLATFORM_SELF_GOVERNANCE_IDENTITY_ADMISSION_AUTHENTICATION_CONTROLS } from "./identity-admission-authentication.mjs";
import { PLATFORM_SELF_GOVERNANCE_PERMISSION_BEHAVIOR_POLICY_CONTROLS } from "./permission-behavior-policy.mjs";
import { PLATFORM_SELF_GOVERNANCE_TRAFFIC_RESOURCE_MANAGEMENT_CONTROLS } from "./traffic-resource-management.mjs";

export const PLATFORM_SELF_GOVERNANCE_CONTROLS = createGovernanceControlMap(
  PLATFORM_SELF_GOVERNANCE_IDENTITY_ADMISSION_AUTHENTICATION_CONTROLS,
  PLATFORM_SELF_GOVERNANCE_PERMISSION_BEHAVIOR_POLICY_CONTROLS,
  PLATFORM_SELF_GOVERNANCE_DATA_STATE_SEMANTICS_CONTROLS,
  PLATFORM_SELF_GOVERNANCE_TRAFFIC_RESOURCE_MANAGEMENT_CONTROLS,
  PLATFORM_SELF_GOVERNANCE_AUDIT_FACT_VERIFICATION_CONTROLS
);
