import { createGovernanceControlMap } from "../control-map.mjs";
import { EXTERNAL_SERVICE_BOUNDARY_ADMISSION_IDENTITY_TRUST_CONTROLS } from "./admission-identity-trust.mjs";
import { EXTERNAL_SERVICE_BOUNDARY_AUDIT_EVIDENCE_LIFECYCLE_CONTROLS } from "./audit-evidence-lifecycle.mjs";
import { EXTERNAL_SERVICE_BOUNDARY_DATA_STATE_SEMANTICS_CONTROLS } from "./data-state-semantics.mjs";
import { EXTERNAL_SERVICE_BOUNDARY_PERMISSION_BEHAVIOR_POLICY_CONTROLS } from "./permission-behavior-policy.mjs";
import { EXTERNAL_SERVICE_BOUNDARY_TRAFFIC_RESOURCE_COST_CONTROLS } from "./traffic-resource-cost.mjs";

export const EXTERNAL_SERVICE_BOUNDARY_GOVERNANCE_CONTROLS = createGovernanceControlMap(
  EXTERNAL_SERVICE_BOUNDARY_ADMISSION_IDENTITY_TRUST_CONTROLS,
  EXTERNAL_SERVICE_BOUNDARY_PERMISSION_BEHAVIOR_POLICY_CONTROLS,
  EXTERNAL_SERVICE_BOUNDARY_DATA_STATE_SEMANTICS_CONTROLS,
  EXTERNAL_SERVICE_BOUNDARY_TRAFFIC_RESOURCE_COST_CONTROLS,
  EXTERNAL_SERVICE_BOUNDARY_AUDIT_EVIDENCE_LIFECYCLE_CONTROLS
);
