import { computed } from "vue";
import { useRoute } from "vue-router";
import { useDebugDistillationController } from "./console-debug-distillation-controller";
import { useServerConsoleShellContext } from "./serverConsoleShellContext";
import type { DebugTab } from "./useConsole";

export function useDebugViewConsole() {
  const {
    agentExploreActiveTabId,
    agentExploreAgentOptions,
    agentExploreAnswerHtml,
    agentExploreDocumentMarkdown,
    agentExploreEventLabel,
    agentExploreEventStatus,
    agentExploreEventTime,
    agentExploreForm,
    agentExploreHistory,
    agentExploreHistoryPanelItems,
    agentExploreLinkedEvidenceRefs,
    agentExploreProgress,
    agentExploreProgressVisible,
    agentExploreResult,
    agentExploreResultKey,
    agentExploreSplitDragging,
    agentExploreSplitLeftPercent,
    agentExploreSplitRef,
    agentExploreSplitStyle,
    agentExploreStepOpen,
    agentExploreStepSummary,
    agentExploreSteps,
    agentExploreTabBusy,
    agentExploreTabMeta,
    agentExploreTabTitle,
    agentExploreTabs,
    agentExploreTraceOpen,
    agentExploreWorkspaceId,
    busyKey,
    closeAgentExploreTab,
    contextWindowOptionBarOptions,
    copyAgentExploreDocument,
    currentView,
    debugTab,
    deleteAgentExploreHistoryItem,
    error,
    exportAgentExploreDocument,
    handleAgentAnswerClick,
    handleAgentExploreSplitKeydown,
    handleAgentExploreTraceToggle,
    highlightedConfigTarget,
    infoFeedModelOptions,
    isAgentExploreDraftSession,
    isAuthenticated,
    jsonPreview,
    knowledgeConsole,
    knowledgeFusionSummary,
    knowledgeRecallDebugForm,
    knowledgeRecallDebugGridStyle,
    knowledgeRecallDebugModeOptionBarOptions,
    knowledgeRecallDebugRuns,
    knowledgeRecallDebugTargetOptions,
    knowledgeSourceState,
    knowledgeStatus,
    openAgentEvidencePreview,
    resetKnowledgeAgentExplore,
    runKnowledgeAgentExplore,
    runKnowledgeRecallDebugBatch,
    selectAgentExploreHistoryItem,
    selectedAgentExploreModel,
    shortId,
    startAgentExploreSplitResize,
    switchAgentExploreTab,
    thinkingModeOptionBarOptions,
    visibleDebugTabs,
  } = useServerConsoleShellContext();

  const route = useRoute();
  const activeDebugTab = computed<DebugTab>(() => {
    const tab = String(route.params.tab ?? "");
    return tab === "knowledgeRecall" || tab === "agentRetrieval" || tab === "knowledgeDistillation"
      ? tab
      : debugTab.value;
  });
  const debugDistillation = useDebugDistillationController({ infoFeedModelOptions });

  return {
    agentExploreActiveTabId,
    agentExploreAgentOptions,
    agentExploreAnswerHtml,
    agentExploreDocumentMarkdown,
    agentExploreEventLabel,
    agentExploreEventStatus,
    agentExploreEventTime,
    agentExploreForm,
    agentExploreHistory,
    agentExploreHistoryPanelItems,
    agentExploreLinkedEvidenceRefs,
    agentExploreProgress,
    agentExploreProgressVisible,
    agentExploreResult,
    agentExploreResultKey,
    agentExploreSplitDragging,
    agentExploreSplitLeftPercent,
    agentExploreSplitRef,
    agentExploreSplitStyle,
    agentExploreStepOpen,
    agentExploreStepSummary,
    agentExploreSteps,
    agentExploreTabBusy,
    agentExploreTabMeta,
    agentExploreTabTitle,
    agentExploreTabs,
    agentExploreTraceOpen,
    agentExploreWorkspaceId,
    busyKey,
    closeAgentExploreTab,
    contextWindowOptionBarOptions,
    copyAgentExploreDocument,
    currentView,
    debugTab,
    deleteAgentExploreHistoryItem,
    error,
    exportAgentExploreDocument,
    handleAgentAnswerClick,
    handleAgentExploreSplitKeydown,
    handleAgentExploreTraceToggle,
    highlightedConfigTarget,
    infoFeedModelOptions,
    isAgentExploreDraftSession,
    isAuthenticated,
    jsonPreview,
    knowledgeConsole,
    knowledgeFusionSummary,
    knowledgeRecallDebugForm,
    knowledgeRecallDebugGridStyle,
    knowledgeRecallDebugModeOptionBarOptions,
    knowledgeRecallDebugRuns,
    knowledgeRecallDebugTargetOptions,
    knowledgeSourceState,
    knowledgeStatus,
    openAgentEvidencePreview,
    resetKnowledgeAgentExplore,
    runKnowledgeAgentExplore,
    runKnowledgeRecallDebugBatch,
    selectAgentExploreHistoryItem,
    selectedAgentExploreModel,
    shortId,
    startAgentExploreSplitResize,
    switchAgentExploreTab,
    thinkingModeOptionBarOptions,
    visibleDebugTabs,
    activeDebugTab,
    ...debugDistillation,
  };
}
