import { createGovernanceControlMap } from "../control-map.mjs";
import { CLIENT_BOUNDARY_AUDIT_FACT_VERIFICATION_CONTROLS } from "./audit-fact-verification.mjs";
import { CLIENT_BOUNDARY_DATA_STATE_SEMANTICS_CONTROLS } from "./data-state-semantics.mjs";
import { CLIENT_BOUNDARY_IDENTITY_ADMISSION_AUTHENTICATION_CONTROLS } from "./identity-admission-authentication.mjs";
import { CLIENT_BOUNDARY_PERMISSION_BEHAVIOR_POLICY_CONTROLS } from "./permission-behavior-policy.mjs";
import { CLIENT_BOUNDARY_TRAFFIC_RESOURCE_MANAGEMENT_CONTROLS } from "./traffic-resource-management.mjs";

export const CLIENT_BOUNDARY_GOVERNANCE_CONTROLS = createGovernanceControlMap(
  CLIENT_BOUNDARY_IDENTITY_ADMISSION_AUTHENTICATION_CONTROLS,
  CLIENT_BOUNDARY_PERMISSION_BEHAVIOR_POLICY_CONTROLS,
  CLIENT_BOUNDARY_DATA_STATE_SEMANTICS_CONTROLS,
  CLIENT_BOUNDARY_TRAFFIC_RESOURCE_MANAGEMENT_CONTROLS,
  CLIENT_BOUNDARY_AUDIT_FACT_VERIFICATION_CONTROLS
);
